dist: bionic
sudo: required
cache: bundler

env:
  global:
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - TNS_ADMIN=$ORACLE_HOME/network/admin
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib
    - DATABASE_VERSION=11.2.0.1
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/Riga' #Needed as a client parameter
    - TZ='Europe/Riga'       #Needed as a DB Server parameter
    - "JRUBY_OPTS='--debug --dev -J-Xmx1024M'"

before_install:
  - chmod +x .travis/oracle/download.sh
  - chmod +x .travis/oracle/install.sh
  - chmod +x .travis/setup_accounts.sh

install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - .travis/setup_accounts.sh
  - ruby -v
  - bundle install

script:
  - bundle exec rake spec
  - rm Gemfile.lock
  - ruby guides/bug_report_templates/active_record_gem.rb
  - ruby guides/bug_report_templates/active_record_gem_spec.rb

language: ruby
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - jruby-9.2.13.0
  - ruby-head
  - jruby-head

notifications:
    email: false
