name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        # Rails 7.0 requires Ruby 2.7 or higeher.
        # CI pending the following matrix until JRuby 9.4 that supports Ruby 2.7 will be released.
        # https://github.com/jruby/jruby/issues/6464
        # - jruby,
        # - jruby-head
        ruby: [
          '3.0',
          '2.7'
        ]
    env:
      ORACLE_HOME: /usr/lib/oracle/18.5/client64
      LD_LIBRARY_PATH: /usr/lib/oracle/18.5/client64/lib
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      TNS_ADMIN: ./ci/network/admin
      DATABASE_NAME: XEPDB1
      TZ: Europe/Riga
      DATABASE_SYS_PASSWORD: Oracle18

    services:
      oracle:
        image: quillbuilduser/oracle-18-xe
        ports:
          - 1521:1521
        env:
          TZ: Europe/Riga
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install required package
      run: |
        sudo apt-get install alien
    - name: Download Oracle client
      run: |
        wget -q https://download.oracle.com/otn_software/linux/instantclient/185000/oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm
        wget -q https://download.oracle.com/otn_software/linux/instantclient/185000/oracle-instantclient18.5-sqlplus-18.5.0.0.0-3.x86_64.rpm
        wget -q https://download.oracle.com/otn_software/linux/instantclient/185000/oracle-instantclient18.5-devel-18.5.0.0.0-3.x86_64.rpm
    - name: Install Oracle client
      run: |
        sudo alien -i oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm
        sudo alien -i oracle-instantclient18.5-sqlplus-18.5.0.0.0-3.x86_64.rpm
        sudo alien -i oracle-instantclient18.5-devel-18.5.0.0.0-3.x86_64.rpm
    - name: Install JDBC Driver
      run: |
        wget -q https://download.oracle.com/otn-pub/otn_software/jdbc/211/ojdbc11.jar -O ./lib/ojdbc11.jar
    - name: Create database user
      run: |
        ./ci/setup_accounts.sh
    - name: Bundle install
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
    - name: Workaround jruby-head failure by removing Gemfile.lock
      run: |
        rm Gemfile.lock
    - name: Run bug report templates
      run: |
        ruby guides/bug_report_templates/active_record_gem.rb
        ruby guides/bug_report_templates/active_record_gem_spec.rb
